### ISSUE TITLE
Permission denied error when switching between methods

### ISSUE THREAD

**Issue by madmodder123** [meleu/RetroPie-joystick-selection#22] opened 2018-03-14 03:45 UTC
RPI3 - RetroPie 4.3,9
When turning the "by-name" method off and then on, the joystick-selection.cfg files fail to update to the global configuration and list Permission Denied errors for all of those files.
So I made sure my version of the script was up to date to make sure that wasn't the problem, but it still happens.
I then tried making all the joystick-selection.cfg files have 777 permissions, that didn't work.
I then made sure all the files had pi as the owner, and that didn't work.
I'm not sure how to solve this issue.

**Comment by meleu** [comment] 2018-03-29 13:44
Try this:

```bash
sudo chown -R pi:pi /opt/retropie/configs
```

**Comment by meleu** [comment] 2018-03-29 13:45
Also, as it's not an issue caused by the tool, I'm closing this issue. Feel free to continue the conversation, though.

**Closed as completed by meleu** 2018-03-29 13:45 UTC
